//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMindV3.Languages {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMindV3.Languages.Langs", typeof(Langs).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Permissions.
        /// </summary>
        internal static string Camera_Permissions {
            get {
                return ResourceManager.GetString("Camera_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have declined permission to use the camera. This will mean you are unable to change your profile image. This can be altered via the settings on your phone..
        /// </summary>
        internal static string Camera_Permissions_Message {
            get {
                return ResourceManager.GetString("Camera_Permissions_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading data.
        /// </summary>
        internal static string Data_DownloadTitle {
            get {
                return ResourceManager.GetString("Data_DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.....
        /// </summary>
        internal static string Data_PleaseWait {
            get {
                return ResourceManager.GetString("Data_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading data.
        /// </summary>
        internal static string Data_UploadingTitle {
            get {
                return ResourceManager.GetString("Data_UploadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Gen_Cancel {
            get {
                return ResourceManager.GetString("Gen_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Gen_Error {
            get {
                return ResourceManager.GetString("Gen_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Gen_OK {
            get {
                return ResourceManager.GetString("Gen_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Gen_Update {
            get {
                return ResourceManager.GetString("Gen_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ICAN number is.
        /// </summary>
        internal static string ICan_Message1 {
            get {
                return ResourceManager.GetString("ICan_Message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter this value on the form..
        /// </summary>
        internal static string ICan_Message2 {
            get {
                return ResourceManager.GetString("ICan_Message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your HCP number is.
        /// </summary>
        internal static string ICan_Message3 {
            get {
                return ResourceManager.GetString("ICan_Message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICAN Details.
        /// </summary>
        internal static string ICan_Title {
            get {
                return ResourceManager.GetString("ICan_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to ICan website.
        /// </summary>
        internal static string Launch_Ican {
            get {
                return ResourceManager.GetString("Launch_Ican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to My Journey.
        /// </summary>
        internal static string Launch_Journey {
            get {
                return ResourceManager.GetString("Launch_Journey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to out of these hours.
        /// </summary>
        internal static string Login_AcceptFour {
            get {
                return ResourceManager.GetString("Login_AcceptFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyMind is a communication app to be used to complete recovery goals, access resources and to contact clinicians for general purposes only. The app is not for contact during a crisis and if I feel at risk I should contact my local CAMHS service directly or the trust 24 hours crisis line on:.
        /// </summary>
        internal static string Login_AcceptOne {
            get {
                return ResourceManager.GetString("Login_AcceptOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand and accept.
        /// </summary>
        internal static string Login_AcceptTerms {
            get {
                return ResourceManager.GetString("Login_AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A+E.
        /// </summary>
        internal static string Login_AcceptThree {
            get {
                return ResourceManager.GetString("Login_AcceptThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can also go directly to my local A+E.
        /// </summary>
        internal static string Login_AcceptTwo {
            get {
                return ResourceManager.GetString("Login_AcceptTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        internal static string Login_EnterName {
            get {
                return ResourceManager.GetString("Login_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string Login_EnterPassword {
            get {
                return ResourceManager.GetString("Login_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not login with the details provided.
        /// </summary>
        internal static string Login_InvalidError {
            get {
                return ResourceManager.GetString("Login_InvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        internal static string Login_Name {
            get {
                return ResourceManager.GetString("Login_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not currently have a network connection.
        /// </summary>
        internal static string Login_NetworkError {
            get {
                return ResourceManager.GetString("Login_NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DON&apos;T HAVE AN ACCOUNT?.
        /// </summary>
        internal static string Login_NoAccount {
            get {
                return ResourceManager.GetString("Login_NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string Login_SignIn {
            get {
                return ResourceManager.GetString("Login_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string Login_SignUp {
            get {
                return ResourceManager.GetString("Login_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your name and password.
        /// </summary>
        internal static string Login_UserPassError {
            get {
                return ResourceManager.GetString("Login_UserPassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your pin code to log back in.
        /// </summary>
        internal static string LoginPincode_Login {
            get {
                return ResourceManager.GetString("LoginPincode_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinicians name.
        /// </summary>
        internal static string MyClinician_ClinName {
            get {
                return ResourceManager.GetString("MyClinician_ClinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinician role.
        /// </summary>
        internal static string MyClinician_ClinRole {
            get {
                return ResourceManager.GetString("MyClinician_ClinRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT NUMBER.
        /// </summary>
        internal static string MyClinician_Contact {
            get {
                return ResourceManager.GetString("MyClinician_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinician fun fact.
        /// </summary>
        internal static string MyClinician_Fact {
            get {
                return ResourceManager.GetString("MyClinician_Fact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUN FACT ABOUT ME.
        /// </summary>
        internal static string MyClinician_FunFact {
            get {
                return ResourceManager.GetString("MyClinician_FunFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinicians number.
        /// </summary>
        internal static string MyClinician_Phone {
            get {
                return ResourceManager.GetString("MyClinician_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Clinician.
        /// </summary>
        internal static string MyClinician_Title {
            get {
                return ResourceManager.GetString("MyClinician_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT I DO.
        /// </summary>
        internal static string MyClinician_WhatIDo {
            get {
                return ResourceManager.GetString("MyClinician_WhatIDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string MyJourney_AlertSelected {
            get {
                return ResourceManager.GetString("MyJourney_AlertSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected.
        /// </summary>
        internal static string MyJourney_AlertSelectedMsg {
            get {
                return ResourceManager.GetString("MyJourney_AlertSelectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appts this month:.
        /// </summary>
        internal static string MyJourney_ApptsMonth {
            get {
                return ResourceManager.GetString("MyJourney_ApptsMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments Summary.
        /// </summary>
        internal static string MyJourney_ApptsSummary {
            get {
                return ResourceManager.GetString("MyJourney_ApptsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appts this week:.
        /// </summary>
        internal static string MyJourney_ApptsWeek {
            get {
                return ResourceManager.GetString("MyJourney_ApptsWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string MyJourney_Date {
            get {
                return ResourceManager.GetString("MyJourney_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string MyJourney_Loc {
            get {
                return ResourceManager.GetString("MyJourney_Loc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome:.
        /// </summary>
        internal static string MyJourney_Outcome {
            get {
                return ResourceManager.GetString("MyJourney_Outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Journey.
        /// </summary>
        internal static string MyJourney_Title {
            get {
                return ResourceManager.GetString("MyJourney_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Chat.
        /// </summary>
        internal static string MyMind_Chat {
            get {
                return ResourceManager.GetString("MyMind_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Clinician.
        /// </summary>
        internal static string MyMind_Clinician {
            get {
                return ResourceManager.GetString("MyMind_Clinician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Journey.
        /// </summary>
        internal static string MyMind_Journey {
            get {
                return ResourceManager.GetString("MyMind_Journey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string MyMind_Logout {
            get {
                return ResourceManager.GetString("MyMind_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Patient Profile.
        /// </summary>
        internal static string MyMind_PatientProfile {
            get {
                return ResourceManager.GetString("MyMind_PatientProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Plans.
        /// </summary>
        internal static string MyMind_Plans {
            get {
                return ResourceManager.GetString("MyMind_Plans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string MyMind_PlansFilename {
            get {
                return ResourceManager.GetString("MyMind_PlansFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string MyMind_PlansType {
            get {
                return ResourceManager.GetString("MyMind_PlansType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Date Time.
        /// </summary>
        internal static string MyMind_PlansUpload {
            get {
                return ResourceManager.GetString("MyMind_PlansUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MyMind_PlansView {
            get {
                return ResourceManager.GetString("MyMind_PlansView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string MyMind_Profile {
            get {
                return ResourceManager.GetString("MyMind_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Resources.
        /// </summary>
        internal static string MyMind_Resources {
            get {
                return ResourceManager.GetString("MyMind_Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session expires.
        /// </summary>
        internal static string MyMind_Session {
            get {
                return ResourceManager.GetString("MyMind_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Mind.
        /// </summary>
        internal static string MyMind_Title {
            get {
                return ResourceManager.GetString("MyMind_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string MyPatient_Details {
            get {
                return ResourceManager.GetString("MyPatient_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string MyPatient_Notes {
            get {
                return ResourceManager.GetString("MyPatient_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the client.
        /// </summary>
        internal static string MyPatient_Select {
            get {
                return ResourceManager.GetString("MyPatient_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Patient Profile.
        /// </summary>
        internal static string MyPatient_Title {
            get {
                return ResourceManager.GetString("MyPatient_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Plans.
        /// </summary>
        internal static string MyPlans_Title {
            get {
                return ResourceManager.GetString("MyPlans_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOMETHING I DISLIKE.
        /// </summary>
        internal static string MyProfile_Dislike {
            get {
                return ResourceManager.GetString("MyProfile_Dislike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE OF BIRTH.
        /// </summary>
        internal static string MyProfile_DOB {
            get {
                return ResourceManager.GetString("MyProfile_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MyProfile_Edit {
            get {
                return ResourceManager.GetString("MyProfile_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter dislikes.
        /// </summary>
        internal static string MyProfile_EnterDislikes {
            get {
                return ResourceManager.GetString("MyProfile_EnterDislikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter date of birth.
        /// </summary>
        internal static string MyProfile_EnterDOB {
            get {
                return ResourceManager.GetString("MyProfile_EnterDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter goals.
        /// </summary>
        internal static string MyProfile_EnterGoals {
            get {
                return ResourceManager.GetString("MyProfile_EnterGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter likes.
        /// </summary>
        internal static string MyProfile_EnterLikes {
            get {
                return ResourceManager.GetString("MyProfile_EnterLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        internal static string MyProfile_EnterName {
            get {
                return ResourceManager.GetString("MyProfile_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone.
        /// </summary>
        internal static string MyProfile_EnterPhone {
            get {
                return ResourceManager.GetString("MyProfile_EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter preferred name.
        /// </summary>
        internal static string MyProfile_EnterPrefName {
            get {
                return ResourceManager.GetString("MyProfile_EnterPrefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter referral reason.
        /// </summary>
        internal static string MyProfile_EnterReason {
            get {
                return ResourceManager.GetString("MyProfile_EnterReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No camera available.
        /// </summary>
        internal static string MyProfile_ErrorCameraMessage {
            get {
                return ResourceManager.GetString("MyProfile_ErrorCameraMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera Error.
        /// </summary>
        internal static string MyProfile_ErrorCameraTitle {
            get {
                return ResourceManager.GetString("MyProfile_ErrorCameraTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOMETHING I LIKE.
        /// </summary>
        internal static string MyProfile_Like {
            get {
                return ResourceManager.GetString("MyProfile_Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string MyProfile_PatientName {
            get {
                return ResourceManager.GetString("MyProfile_PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE NUMBER.
        /// </summary>
        internal static string MyProfile_Phone {
            get {
                return ResourceManager.GetString("MyProfile_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREFERRED NAME.
        /// </summary>
        internal static string MyProfile_PrefName {
            get {
                return ResourceManager.GetString("MyProfile_PrefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string MyProfile_Title {
            get {
                return ResourceManager.GetString("MyProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHAT I WANT TO GET FROM TREATMENT.
        /// </summary>
        internal static string MyProfile_WhatIWant {
            get {
                return ResourceManager.GetString("MyProfile_WhatIWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHY I THINK I WAS REFERRED.
        /// </summary>
        internal static string MyProfile_WhyRefer {
            get {
                return ResourceManager.GetString("MyProfile_WhyRefer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string MyResources_Address {
            get {
                return ResourceManager.GetString("MyResources_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string MyResources_AlertSelected {
            get {
                return ResourceManager.GetString("MyResources_AlertSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected.
        /// </summary>
        internal static string MyResources_AlertSelectedMsg {
            get {
                return ResourceManager.GetString("MyResources_AlertSelectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        internal static string MyResources_Category {
            get {
                return ResourceManager.GetString("MyResources_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information:.
        /// </summary>
        internal static string MyResources_Contact {
            get {
                return ResourceManager.GetString("MyResources_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filter.
        /// </summary>
        internal static string MyResources_FilterOff {
            get {
                return ResourceManager.GetString("MyResources_FilterOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        internal static string MyResources_FilterOn {
            get {
                return ResourceManager.GetString("MyResources_FilterOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string MyResources_Location {
            get {
                return ResourceManager.GetString("MyResources_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referrals:.
        /// </summary>
        internal static string MyResources_Referral {
            get {
                return ResourceManager.GetString("MyResources_Referral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Resources.
        /// </summary>
        internal static string MyResources_Title {
            get {
                return ResourceManager.GetString("MyResources_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Code Login.
        /// </summary>
        internal static string PinCode_Title {
            get {
                return ResourceManager.GetString("PinCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Admin:.
        /// </summary>
        internal static string RegUser_Admin {
            get {
                return ResourceManager.GetString("RegUser_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Authenticated:.
        /// </summary>
        internal static string RegUser_Auth {
            get {
                return ResourceManager.GetString("RegUser_Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string RegUser_Email {
            get {
                return ResourceManager.GetString("RegUser_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string RegUser_Name {
            get {
                return ResourceManager.GetString("RegUser_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        internal static string RegUser_Phone {
            get {
                return ResourceManager.GetString("RegUser_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTERED USERS - ADMIN ONLY.
        /// </summary>
        internal static string RegUser_Title {
            get {
                return ResourceManager.GetString("RegUser_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Registered Users:.
        /// </summary>
        internal static string RegUser_TotalReg {
            get {
                return ResourceManager.GetString("RegUser_TotalReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID:.
        /// </summary>
        internal static string RegUser_UserID {
            get {
                return ResourceManager.GetString("RegUser_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete all fields.
        /// </summary>
        internal static string SignUp_AllFieldsError {
            get {
                return ResourceManager.GetString("SignUp_AllFieldsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATE OF BIRTH.
        /// </summary>
        internal static string SignUp_DOB {
            get {
                return ResourceManager.GetString("SignUp_DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL.
        /// </summary>
        internal static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        internal static string SignUp_EnterEmail {
            get {
                return ResourceManager.GetString("SignUp_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name.
        /// </summary>
        internal static string SignUp_EnterName {
            get {
                return ResourceManager.GetString("SignUp_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string SignUp_EnterPassword {
            get {
                return ResourceManager.GetString("SignUp_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone.
        /// </summary>
        internal static string SignUp_EnterPhone {
            get {
                return ResourceManager.GetString("SignUp_EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a pincode.
        /// </summary>
        internal static string SignUp_EnterPin {
            get {
                return ResourceManager.GetString("SignUp_EnterPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter preferred name.
        /// </summary>
        internal static string SignUp_EnterPrefName {
            get {
                return ResourceManager.GetString("SignUp_EnterPrefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        internal static string SignUp_EnterRepPassword {
            get {
                return ResourceManager.GetString("SignUp_EnterRepPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALREADY HAVE AN ACCOUNT?.
        /// </summary>
        internal static string SignUp_HaveAcc {
            get {
                return ResourceManager.GetString("SignUp_HaveAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME.
        /// </summary>
        internal static string SignUp_Name {
            get {
                return ResourceManager.GetString("SignUp_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        internal static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string SignUp_Phone {
            get {
                return ResourceManager.GetString("SignUp_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN CODE.
        /// </summary>
        internal static string SignUp_Pin {
            get {
                return ResourceManager.GetString("SignUp_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred NAME.
        /// </summary>
        internal static string SignUp_PrefName {
            get {
                return ResourceManager.GetString("SignUp_PrefName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPEAT PASSWORD.
        /// </summary>
        internal static string SignUp_RepPassword {
            get {
                return ResourceManager.GetString("SignUp_RepPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN IN.
        /// </summary>
        internal static string SignUp_SignIn {
            get {
                return ResourceManager.GetString("SignUp_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp_Title {
            get {
                return ResourceManager.GetString("SignUp_Title", resourceCulture);
            }
        }
    }
}
