// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MyMindV3.Languages {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langs {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MyMindV3.Languages.Langs", typeof(Langs).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Gen_OK {
            get {
                return ResourceManager.GetString("Gen_OK", resourceCulture);
            }
        }
        
        public static string Gen_Error {
            get {
                return ResourceManager.GetString("Gen_Error", resourceCulture);
            }
        }
        
        public static string Gen_Cancel {
            get {
                return ResourceManager.GetString("Gen_Cancel", resourceCulture);
            }
        }
        
        public static string Gen_Update {
            get {
                return ResourceManager.GetString("Gen_Update", resourceCulture);
            }
        }
        
        public static string Gen_PleaseWait {
            get {
                return ResourceManager.GetString("Gen_PleaseWait", resourceCulture);
            }
        }
        
        public static string Menu_Resources {
            get {
                return ResourceManager.GetString("Menu_Resources", resourceCulture);
            }
        }
        
        public static string Menu_AveRating {
            get {
                return ResourceManager.GetString("Menu_AveRating", resourceCulture);
            }
        }
        
        public static string Menu_AZ {
            get {
                return ResourceManager.GetString("Menu_AZ", resourceCulture);
            }
        }
        
        public static string Menu_Popular {
            get {
                return ResourceManager.GetString("Menu_Popular", resourceCulture);
            }
        }
        
        public static string Login_EnterName {
            get {
                return ResourceManager.GetString("Login_EnterName", resourceCulture);
            }
        }
        
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        public static string Login_Name {
            get {
                return ResourceManager.GetString("Login_Name", resourceCulture);
            }
        }
        
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        public static string Login_EnterPassword {
            get {
                return ResourceManager.GetString("Login_EnterPassword", resourceCulture);
            }
        }
        
        public static string Login_SignIn {
            get {
                return ResourceManager.GetString("Login_SignIn", resourceCulture);
            }
        }
        
        public static string Login_AcceptOne {
            get {
                return ResourceManager.GetString("Login_AcceptOne", resourceCulture);
            }
        }
        
        public static string Login_AcceptTwo {
            get {
                return ResourceManager.GetString("Login_AcceptTwo", resourceCulture);
            }
        }
        
        public static string Login_AcceptThree {
            get {
                return ResourceManager.GetString("Login_AcceptThree", resourceCulture);
            }
        }
        
        public static string Login_AcceptFour {
            get {
                return ResourceManager.GetString("Login_AcceptFour", resourceCulture);
            }
        }
        
        public static string Login_AcceptTerms {
            get {
                return ResourceManager.GetString("Login_AcceptTerms", resourceCulture);
            }
        }
        
        public static string Login_SignUp {
            get {
                return ResourceManager.GetString("Login_SignUp", resourceCulture);
            }
        }
        
        public static string Login_NoAccount {
            get {
                return ResourceManager.GetString("Login_NoAccount", resourceCulture);
            }
        }
        
        public static string RegUser_Title {
            get {
                return ResourceManager.GetString("RegUser_Title", resourceCulture);
            }
        }
        
        public static string RegUser_Name {
            get {
                return ResourceManager.GetString("RegUser_Name", resourceCulture);
            }
        }
        
        public static string RegUser_Email {
            get {
                return ResourceManager.GetString("RegUser_Email", resourceCulture);
            }
        }
        
        public static string RegUser_UserID {
            get {
                return ResourceManager.GetString("RegUser_UserID", resourceCulture);
            }
        }
        
        public static string RegUser_Phone {
            get {
                return ResourceManager.GetString("RegUser_Phone", resourceCulture);
            }
        }
        
        public static string RegUser_Auth {
            get {
                return ResourceManager.GetString("RegUser_Auth", resourceCulture);
            }
        }
        
        public static string RegUser_Admin {
            get {
                return ResourceManager.GetString("RegUser_Admin", resourceCulture);
            }
        }
        
        public static string RegUser_TotalReg {
            get {
                return ResourceManager.GetString("RegUser_TotalReg", resourceCulture);
            }
        }
        
        public static string PinCode_Title {
            get {
                return ResourceManager.GetString("PinCode_Title", resourceCulture);
            }
        }
        
        public static string MyClinician_Title {
            get {
                return ResourceManager.GetString("MyClinician_Title", resourceCulture);
            }
        }
        
        public static string MyClinician_WhatIDo {
            get {
                return ResourceManager.GetString("MyClinician_WhatIDo", resourceCulture);
            }
        }
        
        public static string MyClinician_ClinName {
            get {
                return ResourceManager.GetString("MyClinician_ClinName", resourceCulture);
            }
        }
        
        public static string MyClinician_ClinRole {
            get {
                return ResourceManager.GetString("MyClinician_ClinRole", resourceCulture);
            }
        }
        
        public static string MyClinician_FunFact {
            get {
                return ResourceManager.GetString("MyClinician_FunFact", resourceCulture);
            }
        }
        
        public static string MyClinician_Fact {
            get {
                return ResourceManager.GetString("MyClinician_Fact", resourceCulture);
            }
        }
        
        public static string MyClinician_Contact {
            get {
                return ResourceManager.GetString("MyClinician_Contact", resourceCulture);
            }
        }
        
        public static string MyClinician_Phone {
            get {
                return ResourceManager.GetString("MyClinician_Phone", resourceCulture);
            }
        }
        
        public static string MyJourney_Title {
            get {
                return ResourceManager.GetString("MyJourney_Title", resourceCulture);
            }
        }
        
        public static string MyJourney_ApptsSummary {
            get {
                return ResourceManager.GetString("MyJourney_ApptsSummary", resourceCulture);
            }
        }
        
        public static string MyJourney_ApptsWeek {
            get {
                return ResourceManager.GetString("MyJourney_ApptsWeek", resourceCulture);
            }
        }
        
        public static string MyJourney_ApptsMonth {
            get {
                return ResourceManager.GetString("MyJourney_ApptsMonth", resourceCulture);
            }
        }
        
        public static string MyJourney_Date {
            get {
                return ResourceManager.GetString("MyJourney_Date", resourceCulture);
            }
        }
        
        public static string MyJourney_Loc {
            get {
                return ResourceManager.GetString("MyJourney_Loc", resourceCulture);
            }
        }
        
        public static string MyJourney_Outcome {
            get {
                return ResourceManager.GetString("MyJourney_Outcome", resourceCulture);
            }
        }
        
        public static string MyJourney_AlertSelected {
            get {
                return ResourceManager.GetString("MyJourney_AlertSelected", resourceCulture);
            }
        }
        
        public static string MyJourney_AlertSelectedMsg {
            get {
                return ResourceManager.GetString("MyJourney_AlertSelectedMsg", resourceCulture);
            }
        }
        
        public static string MyMind_Title {
            get {
                return ResourceManager.GetString("MyMind_Title", resourceCulture);
            }
        }
        
        public static string MyMind_Session {
            get {
                return ResourceManager.GetString("MyMind_Session", resourceCulture);
            }
        }
        
        public static string MyMind_Profile {
            get {
                return ResourceManager.GetString("MyMind_Profile", resourceCulture);
            }
        }
        
        public static string MyMind_PatientProfile {
            get {
                return ResourceManager.GetString("MyMind_PatientProfile", resourceCulture);
            }
        }
        
        public static string MyMind_Resources {
            get {
                return ResourceManager.GetString("MyMind_Resources", resourceCulture);
            }
        }
        
        public static string MyMind_Clinician {
            get {
                return ResourceManager.GetString("MyMind_Clinician", resourceCulture);
            }
        }
        
        public static string MyMind_Journey {
            get {
                return ResourceManager.GetString("MyMind_Journey", resourceCulture);
            }
        }
        
        public static string MyMind_Chat {
            get {
                return ResourceManager.GetString("MyMind_Chat", resourceCulture);
            }
        }
        
        public static string MyMind_Plans {
            get {
                return ResourceManager.GetString("MyMind_Plans", resourceCulture);
            }
        }
        
        public static string MyMind_PlansFilename {
            get {
                return ResourceManager.GetString("MyMind_PlansFilename", resourceCulture);
            }
        }
        
        public static string MyMind_PlansType {
            get {
                return ResourceManager.GetString("MyMind_PlansType", resourceCulture);
            }
        }
        
        public static string MyMind_PlansUpload {
            get {
                return ResourceManager.GetString("MyMind_PlansUpload", resourceCulture);
            }
        }
        
        public static string MyMind_PlansView {
            get {
                return ResourceManager.GetString("MyMind_PlansView", resourceCulture);
            }
        }
        
        public static string MyMind_Logout {
            get {
                return ResourceManager.GetString("MyMind_Logout", resourceCulture);
            }
        }
        
        public static string MyPlans_Title {
            get {
                return ResourceManager.GetString("MyPlans_Title", resourceCulture);
            }
        }
        
        public static string MyProfile_Title {
            get {
                return ResourceManager.GetString("MyProfile_Title", resourceCulture);
            }
        }
        
        public static string MyProfile_PrefName {
            get {
                return ResourceManager.GetString("MyProfile_PrefName", resourceCulture);
            }
        }
        
        public static string MyProfile_PatientName {
            get {
                return ResourceManager.GetString("MyProfile_PatientName", resourceCulture);
            }
        }
        
        public static string MyProfile_DOB {
            get {
                return ResourceManager.GetString("MyProfile_DOB", resourceCulture);
            }
        }
        
        public static string MyProfile_Phone {
            get {
                return ResourceManager.GetString("MyProfile_Phone", resourceCulture);
            }
        }
        
        public static string MyProfile_WhyRefer {
            get {
                return ResourceManager.GetString("MyProfile_WhyRefer", resourceCulture);
            }
        }
        
        public static string MyProfile_Like {
            get {
                return ResourceManager.GetString("MyProfile_Like", resourceCulture);
            }
        }
        
        public static string MyProfile_Dislike {
            get {
                return ResourceManager.GetString("MyProfile_Dislike", resourceCulture);
            }
        }
        
        public static string MyProfile_WhatIWant {
            get {
                return ResourceManager.GetString("MyProfile_WhatIWant", resourceCulture);
            }
        }
        
        public static string MyProfile_Edit {
            get {
                return ResourceManager.GetString("MyProfile_Edit", resourceCulture);
            }
        }
        
        public static string MyProfile_EnterName {
            get {
                return ResourceManager.GetString("MyProfile_EnterName", resourceCulture);
            }
        }
        
        public static string MyProfile_EnterPrefName {
            get {
                return ResourceManager.GetString("MyProfile_EnterPrefName", resourceCulture);
            }
        }
        
        public static string MyProfile_EnterDOB {
            get {
                return ResourceManager.GetString("MyProfile_EnterDOB", resourceCulture);
            }
        }
        
        public static string MyProfile_EnterPhone {
            get {
                return ResourceManager.GetString("MyProfile_EnterPhone", resourceCulture);
            }
        }
        
        public static string MyProfile_EnterReason {
            get {
                return ResourceManager.GetString("MyProfile_EnterReason", resourceCulture);
            }
        }
        
        public static string MyProfile_EnterLikes {
            get {
                return ResourceManager.GetString("MyProfile_EnterLikes", resourceCulture);
            }
        }
        
        public static string MyProfile_EnterDislikes {
            get {
                return ResourceManager.GetString("MyProfile_EnterDislikes", resourceCulture);
            }
        }
        
        public static string MyProfile_EnterGoals {
            get {
                return ResourceManager.GetString("MyProfile_EnterGoals", resourceCulture);
            }
        }
        
        public static string MyProfile_ErrorCameraTitle {
            get {
                return ResourceManager.GetString("MyProfile_ErrorCameraTitle", resourceCulture);
            }
        }
        
        public static string MyProfile_ErrorCameraMessage {
            get {
                return ResourceManager.GetString("MyProfile_ErrorCameraMessage", resourceCulture);
            }
        }
        
        public static string MyResources_Title {
            get {
                return ResourceManager.GetString("MyResources_Title", resourceCulture);
            }
        }
        
        public static string MyResources_Postcode {
            get {
                return ResourceManager.GetString("MyResources_Postcode", resourceCulture);
            }
        }
        
        public static string MyResources_GettingResources {
            get {
                return ResourceManager.GetString("MyResources_GettingResources", resourceCulture);
            }
        }
        
        public static string MyResources_Location {
            get {
                return ResourceManager.GetString("MyResources_Location", resourceCulture);
            }
        }
        
        public static string MyResources_Rated {
            get {
                return ResourceManager.GetString("MyResources_Rated", resourceCulture);
            }
        }
        
        public static string MyResources_Category {
            get {
                return ResourceManager.GetString("MyResources_Category", resourceCulture);
            }
        }
        
        public static string MyResources_Distance {
            get {
                return ResourceManager.GetString("MyResources_Distance", resourceCulture);
            }
        }
        
        public static string MyResources_Miles {
            get {
                return ResourceManager.GetString("MyResources_Miles", resourceCulture);
            }
        }
        
        public static string MyResources_Address {
            get {
                return ResourceManager.GetString("MyResources_Address", resourceCulture);
            }
        }
        
        public static string MyResources_Referral {
            get {
                return ResourceManager.GetString("MyResources_Referral", resourceCulture);
            }
        }
        
        public static string MyResources_Contact {
            get {
                return ResourceManager.GetString("MyResources_Contact", resourceCulture);
            }
        }
        
        public static string MyResources_AlertSelected {
            get {
                return ResourceManager.GetString("MyResources_AlertSelected", resourceCulture);
            }
        }
        
        public static string MyResources_AlertSelectedMsg {
            get {
                return ResourceManager.GetString("MyResources_AlertSelectedMsg", resourceCulture);
            }
        }
        
        public static string MyResources_FilterOn {
            get {
                return ResourceManager.GetString("MyResources_FilterOn", resourceCulture);
            }
        }
        
        public static string MyResources_FilterOff {
            get {
                return ResourceManager.GetString("MyResources_FilterOff", resourceCulture);
            }
        }
        
        public static string MyResources_Previous {
            get {
                return ResourceManager.GetString("MyResources_Previous", resourceCulture);
            }
        }
        
        public static string MyResources_Next {
            get {
                return ResourceManager.GetString("MyResources_Next", resourceCulture);
            }
        }
        
        public static string SignUp_Title {
            get {
                return ResourceManager.GetString("SignUp_Title", resourceCulture);
            }
        }
        
        public static string SignUp_Name {
            get {
                return ResourceManager.GetString("SignUp_Name", resourceCulture);
            }
        }
        
        public static string SignUp_PrefName {
            get {
                return ResourceManager.GetString("SignUp_PrefName", resourceCulture);
            }
        }
        
        public static string SignUp_Email {
            get {
                return ResourceManager.GetString("SignUp_Email", resourceCulture);
            }
        }
        
        public static string SignUp_DOB {
            get {
                return ResourceManager.GetString("SignUp_DOB", resourceCulture);
            }
        }
        
        public static string SignUp_Password {
            get {
                return ResourceManager.GetString("SignUp_Password", resourceCulture);
            }
        }
        
        public static string SignUp_RepPassword {
            get {
                return ResourceManager.GetString("SignUp_RepPassword", resourceCulture);
            }
        }
        
        public static string SignUp_Phone {
            get {
                return ResourceManager.GetString("SignUp_Phone", resourceCulture);
            }
        }
        
        public static string SignUp_Pin {
            get {
                return ResourceManager.GetString("SignUp_Pin", resourceCulture);
            }
        }
        
        public static string SignUp_EnterName {
            get {
                return ResourceManager.GetString("SignUp_EnterName", resourceCulture);
            }
        }
        
        public static string SignUp_EnterPrefName {
            get {
                return ResourceManager.GetString("SignUp_EnterPrefName", resourceCulture);
            }
        }
        
        public static string SignUp_EnterEmail {
            get {
                return ResourceManager.GetString("SignUp_EnterEmail", resourceCulture);
            }
        }
        
        public static string SignUp_EnterPassword {
            get {
                return ResourceManager.GetString("SignUp_EnterPassword", resourceCulture);
            }
        }
        
        public static string SignUp_EnterRepPassword {
            get {
                return ResourceManager.GetString("SignUp_EnterRepPassword", resourceCulture);
            }
        }
        
        public static string SignUp_EnterPhone {
            get {
                return ResourceManager.GetString("SignUp_EnterPhone", resourceCulture);
            }
        }
        
        public static string SignUp_EnterPin {
            get {
                return ResourceManager.GetString("SignUp_EnterPin", resourceCulture);
            }
        }
        
        public static string SignUp_HaveAcc {
            get {
                return ResourceManager.GetString("SignUp_HaveAcc", resourceCulture);
            }
        }
        
        public static string SignUp_SignIn {
            get {
                return ResourceManager.GetString("SignUp_SignIn", resourceCulture);
            }
        }
        
        public static string Launch_Ican {
            get {
                return ResourceManager.GetString("Launch_Ican", resourceCulture);
            }
        }
        
        public static string Launch_Journey {
            get {
                return ResourceManager.GetString("Launch_Journey", resourceCulture);
            }
        }
        
        public static string LoginPincode_Login {
            get {
                return ResourceManager.GetString("LoginPincode_Login", resourceCulture);
            }
        }
        
        public static string Login_UserPassError {
            get {
                return ResourceManager.GetString("Login_UserPassError", resourceCulture);
            }
        }
        
        public static string Login_InvalidError {
            get {
                return ResourceManager.GetString("Login_InvalidError", resourceCulture);
            }
        }
        
        public static string Login_NetworkError {
            get {
                return ResourceManager.GetString("Login_NetworkError", resourceCulture);
            }
        }
        
        public static string SignUp_AllFieldsError {
            get {
                return ResourceManager.GetString("SignUp_AllFieldsError", resourceCulture);
            }
        }
        
        public static string Data_UploadingTitle {
            get {
                return ResourceManager.GetString("Data_UploadingTitle", resourceCulture);
            }
        }
        
        public static string Data_DownloadTitle {
            get {
                return ResourceManager.GetString("Data_DownloadTitle", resourceCulture);
            }
        }
        
        public static string Data_PleaseWait {
            get {
                return ResourceManager.GetString("Data_PleaseWait", resourceCulture);
            }
        }
        
        public static string MyPatient_Title {
            get {
                return ResourceManager.GetString("MyPatient_Title", resourceCulture);
            }
        }
        
        public static string MyPatient_Details {
            get {
                return ResourceManager.GetString("MyPatient_Details", resourceCulture);
            }
        }
        
        public static string MyPatient_Select {
            get {
                return ResourceManager.GetString("MyPatient_Select", resourceCulture);
            }
        }
        
        public static string MyPatient_Notes {
            get {
                return ResourceManager.GetString("MyPatient_Notes", resourceCulture);
            }
        }
        
        public static string ICan_Title {
            get {
                return ResourceManager.GetString("ICan_Title", resourceCulture);
            }
        }
        
        public static string ICan_Message1 {
            get {
                return ResourceManager.GetString("ICan_Message1", resourceCulture);
            }
        }
        
        public static string ICan_Message2 {
            get {
                return ResourceManager.GetString("ICan_Message2", resourceCulture);
            }
        }
        
        public static string ICan_Message3 {
            get {
                return ResourceManager.GetString("ICan_Message3", resourceCulture);
            }
        }
        
        public static string Camera_Permissions {
            get {
                return ResourceManager.GetString("Camera_Permissions", resourceCulture);
            }
        }
        
        public static string Camera_Permissions_Message {
            get {
                return ResourceManager.GetString("Camera_Permissions_Message", resourceCulture);
            }
        }
        
        public static string Error_NetworkTitle {
            get {
                return ResourceManager.GetString("Error_NetworkTitle", resourceCulture);
            }
        }
        
        public static string Error_PostcodeMessage {
            get {
                return ResourceManager.GetString("Error_PostcodeMessage", resourceCulture);
            }
        }
        
        public static string Error_GeolocationMessage {
            get {
                return ResourceManager.GetString("Error_GeolocationMessage", resourceCulture);
            }
        }
        
        public static string LoggingIn_Title {
            get {
                return ResourceManager.GetString("LoggingIn_Title", resourceCulture);
            }
        }
        
        public static string Registration_ErrorMessage {
            get {
                return ResourceManager.GetString("Registration_ErrorMessage", resourceCulture);
            }
        }
        
        public static string Message_UploadingMessage {
            get {
                return ResourceManager.GetString("Message_UploadingMessage", resourceCulture);
            }
        }
        
        public static string Message_UploadingTitle {
            get {
                return ResourceManager.GetString("Message_UploadingTitle", resourceCulture);
            }
        }
    }
}
